### ISSUE TITLE
Feature request :) - Shortcut for copying current open pivotal link in markdown form

### ISSUE THREAD

**Issue by kcolton** [tomoyukikashiro/pivotaltracker-ex-keyboard-shortcuts_chrome-extension#9]
**Feature request:** Keyboard shortcut to copy something like this into the clipboard for easy pasting into github  `[PT#134233507](https://www.pivotaltracker.com/story/show/134233507)` because I am lazy

Haha - This is tempting me to make chrome extensions for all the quirks on sites that annoy me

**Comment by kcolton** [comment]
Whats pivotal? (closing)

**Comment by t-jindai** [comment]
I've already done it . 👍 sorry for not mention you 😅 
https://github.com/tomoyukikashiro/pivotaltracker-ex-keyboard-shortcuts_chrome-extension/pull/13

@kcolton
